create table jogador (id int8 generated by default as identity, assistencia int4, gol int4, image varchar(255), nome varchar(255), posicao varchar(255), primary key (id));
create table partida (id int8 generated by default as identity, data_jogo date, gols_adversario int4, gols_raca int4, local varchar(255), time_adversario varchar(255), time_raca varchar(255), primary key (id));
INSERT INTO jogador(nome, gol, assistencia, posicao) VALUES('Cristiano', 14, 6, 'ala');
INSERT INTO jogador(nome, gol, assistencia, posicao) VALUES('Leandro', 13, 3, 'ala');
